[OpenAI]
# Default options: openai, azure
API_TYPE=openai

# The main text generation model, used for agent responses
MODEL=moonshotai/kimi-k2-instruct
MAX_COMPLETION_TOKENS=4096

[Cognition]
enable_memory_consolidation = False
enable_continuous_contextual_semantic_memory_retrieval = False

[Logging]
loglevel = ERROR
loglevel_console = INFO
loglevel_file = DEBUG
