"""Catalog contracts and data for bounded enterprise world facts."""

from open_range.catalog.contracts import (
    OBJECTIVE_RESOLUTION_KINDS,
    STANDARD_ATTACK_OBJECTIVE_NAMES,
    ObjectiveGraderKind,
    ObjectiveResolutionKind,
    ObjectiveRuleSpec,
    ServiceCatalogEntry,
    StandardAttackObjective,
    WeaknessObjectiveTagSpec,
    WeaknessObservabilitySurfaceSpec,
)
from open_range.catalog.objectives import (
    OBJECTIVE_RULE_SPECS,
    WEAKNESS_OBJECTIVE_TAG_SPECS,
    objective_rule_for_predicate_name,
    public_objective_predicate_names,
    weakness_objective_tags_for_kind,
)
from open_range.catalog.services import (
    ROLE_HOME_SERVICE_BY_ROLE,
    SERVICE_CATALOG,
    host_for_service,
    service_catalog_entry_for_id,
    service_catalog_entry_for_kind,
    service_kind_names,
)
from open_range.catalog.weaknesses import (
    WEAKNESS_EXPECTED_EVENT_SPECS,
    WEAKNESS_FAMILY_CONTRACTS,
    WEAKNESS_OBSERVABILITY_SURFACE_SPECS,
    available_weakness_families_for_service_kinds,
    benchmark_tags_for_family,
    default_target_kind_for_family,
    expected_events_for_weakness,
    instantiation_mode_for_family,
    observability_surfaces_for_weakness,
    precondition_mode_for_family,
    weakness_family_contract,
)

__all__ = [
    "OBJECTIVE_RESOLUTION_KINDS",
    "OBJECTIVE_RULE_SPECS",
    "STANDARD_ATTACK_OBJECTIVE_NAMES",
    "WEAKNESS_OBJECTIVE_TAG_SPECS",
    "WEAKNESS_EXPECTED_EVENT_SPECS",
    "WEAKNESS_FAMILY_CONTRACTS",
    "WEAKNESS_OBSERVABILITY_SURFACE_SPECS",
    "ObjectiveGraderKind",
    "ObjectiveResolutionKind",
    "ObjectiveRuleSpec",
    "ROLE_HOME_SERVICE_BY_ROLE",
    "SERVICE_CATALOG",
    "ServiceCatalogEntry",
    "StandardAttackObjective",
    "WeaknessObservabilitySurfaceSpec",
    "WeaknessObjectiveTagSpec",
    "available_weakness_families_for_service_kinds",
    "benchmark_tags_for_family",
    "default_target_kind_for_family",
    "expected_events_for_weakness",
    "host_for_service",
    "instantiation_mode_for_family",
    "objective_rule_for_predicate_name",
    "observability_surfaces_for_weakness",
    "precondition_mode_for_family",
    "public_objective_predicate_names",
    "service_catalog_entry_for_id",
    "service_catalog_entry_for_kind",
    "service_kind_names",
    "weakness_family_contract",
    "weakness_objective_tags_for_kind",
]
