"""Backward-compatible shim for the packaged manifest schema."""

from open_range.manifest_schema import (
    BusinessProcess,
    Company,
    CredentialPolicy,
    DataAsset,
    Department,
    Difficulty,
    ExposurePolicy,
    FirewallRule,
    Host,
    Manifest,
    MonitoringCoverage,
    NPCProfile,
    Network,
    OperationalContext,
    TechStack,
    Topology,
    TrustRelationship,
    User,
    load_manifest,
)

__all__ = [
    "BusinessProcess",
    "Company",
    "CredentialPolicy",
    "DataAsset",
    "Department",
    "Difficulty",
    "ExposurePolicy",
    "FirewallRule",
    "Host",
    "Manifest",
    "MonitoringCoverage",
    "NPCProfile",
    "Network",
    "OperationalContext",
    "TechStack",
    "Topology",
    "TrustRelationship",
    "User",
    "load_manifest",
]
