{{- if .Values.users }}
{{- range $zoneName, $zone := .Values.zones }}
apiVersion: v1
kind: Secret
metadata:
  name: user-credentials
  namespace: {{ $.Values.global.namePrefix }}-{{ $zoneName }}
  labels:
    {{- include "openrange.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $.Values.users }}
  {{ .username }}: {{ .password | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
